### ISSUE TITLE
The source field for Diagnostics shouldn't be relative Uri

### ISSUE THREAD

**Issue by jiahuijiang** [palantir/language-servers#122]
It should be a human readable string

https://github.com/TypeFox/ls-api/blob/e83d3dde2d5bd5e2bb261779d5bfc3df1f7a0366/io.typefox.lsapi/src/main/java/io/typefox/lsapi/Diagnostic.xtend

**Comment by natgabb** [comment]
We should just use the default source `groovyc` all the time.
