### ISSUE TITLE
didChange shouldn't recompile

### ISSUE THREAD

**Issue by ags799** [palantir/language-servers#144]
We respond to `textDocument/didChange` with a [recompile](https://github.com/palantir/language-servers/blob/develop/language-server-commons/src/main/java/com/palantir/ls/services/AbstractTextDocumentService.java#L86).

We should only compile on `textDocument/didSave`.

**Comment by natgabb** [comment]
If `textDocument/didChange` doesn't recompile, how do you get compilation and syntax errors on unsaved changes?

Also, if you no longer want to compile these incremental changes, keeping track of the changes with `SourceWriter` becomes useless.

**Comment by ags799** [comment]
natacha!

**Comment by ags799** [comment]
compiling on every change introduces performance concerns

**Comment by natgabb** [comment]
Andrew! 😄 
Might be worth looking into compiling only after X amount of time has passed if you're sending a lot of `textDocument/didChange`. Otherwise I think you should consider removing keeping track of incremental changes for now since its not being used.

**Comment by darora** [comment]
Aside from the option of doing that, you'd still want unsaved state for things like completions

**Comment by jiahuijiang** [comment]
feel we should just ask the frontend to send accumulated changes every 5 second, otherwise our language servers won't work with anything that doesn't have autosave

**Comment by ags799** [comment]
we aren't the first to do this: javac LS doesn't recompile on change, only on save

**Comment by darora** [comment]
Agree that that's a concern, but right now our contract is pretty simple. 

You save-you get diagnostics.

What would be the equivalent? Send changes every 5 seconds, BUT also if the user asks for completions, AND also if the user saves, AND {insert case I haven't thought of}

**Comment by natgabb** [comment]
Completion uses the symbols in the `CompilerWrapper` but these are only updated when the code is compiled. This is because symbols are parsed from the successfully compiled AST (see: https://github.com/palantir/language-servers/blob/c485a6b216f66859cd43960962c74cf146742cf6/language-server-commons/src/main/java/com/palantir/ls/DefaultCompilerWrapper.java#L93). If there are changes written to file by `SourceWriter` they will not be reflected in the symbols.
An alternative would be to compile when a completion request is received, but that might make it laggy and is IMO not the best approach.

**Comment by ags799** [comment]
updated symbols aside, it's still important to use didChange notifications to update the document because [completion requests](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#completion-request) only provide text document positions

so although our symbols may be out of date, our document won't, & we'll be able to service completion requests using the set of symbols parsed on last save

**Comment by natgabb** [comment]
That's a good point but for a different reason: the text document positions are not compared to the file that `SourceWriter` keeps track of, they are compared to the Symbols that are stored - which are (now) based on the old version of the file! So everything from completion to goto definition will not work correctly.

**Comment by ags799** [comment]
maybe we should change that, maybe text document positions should be compared to the SourceWriter?

**Comment by natgabb** [comment]
How do you provide semantic meaning to a plain text file? Using a compiler. That's already what we're doing. There's really no way around this.
