### ISSUE TITLE
Update ls-api version

### ISSUE THREAD

**Issue by jiahuijiang** [palantir/language-servers#150]
ls-api has been moved to https://github.com/eclipse/lsp4j and renamed

**Comment by natgabb** [comment]
Btw they removed builders in lsp4j: https://github.com/TypeFox/ls-api/issues/37 so it'll be a bit of a refactor.

**Comment by jiahuijiang** [comment]
blocked by https://github.com/eclipse/lsp4j/issues/23

**Comment by jiahuijiang** [comment]
lol yep... and probably the next release they will add it back @@
