### ISSUE TITLE
Missing logger dependency for Groovy language server?

### ISSUE THREAD

**Issue by moritzheiber** [palantir/language-servers#172]
I'm not sure why this is failing for me, I'm using one of the builds from Bintray:

```
$ java -jar groovy-language-server-0.5.3-all.jar 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

This seems to be related to #31, however, that one appears to be resolved since years ago.

Any pointers would be appreciated.

**Comment by jiahuijiang** [comment]
Thanks for reporting! We recently switched the project to use logback.xml but forgot to change the dependency. This is fixed in #173. Will cut a release once it passed CR!
