### ISSUE TITLE
Split up GroovycWrapper

### ISSUE THREAD

**Issue by natgabb** [palantir/language-servers#84]
One part should implement getting compilation errors and generating an AST, and another part should be parsing symbols, references, etc from a given AST.

**Comment by gracew** [comment]
+1

the part that generates the AST should not involve any typefox APIs.

**Comment by natgabb** [comment]
@gracew: If we don't depend on ls-api, we might have to reimplement the Diagnostic interface, and then do a conversion when publishing. Are we okay with that?
